# Generated by Django 4.0.5 on 2022-08-23 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='regmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.IntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('bio', models.CharField(max_length=1000)),
                ('occupation', models.CharField(max_length=100)),
                ('looking_for', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='static')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
