# Generated by Django 4.0.5 on 2022-08-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonial_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regmodel',
            old_name='photo',
            new_name='image',
        ),
        migrations.AddField(
            model_name='regmodel',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
